### ISSUE TITLE
the omnifunc is githubissues#CompleteIssues

### ISSUE THREAD

**Issue by eduOS** [rhysd/github-complete.vim#2]
Thanks for the great repo.

I followed the install tutorial but failed to reconcile this with github-issue on omnifunc. I'm wondering whether the set of github-issue will fail if omnifunc is set as github_complete#complete.

**Comment by rhysd** [comment]
I checked github-issues.vim.  Please use [`g:github_issues_no_omni`](https://github.com/jaxbot/github-issues.vim/blob/ce024c01f3fc460325b40e748e111e63c86e1310/plugin/githubissues.vim#L272)

I think it can solve this issue so I'll close this issue.  If you still have a problem, please reopen this issue.

**Comment by rhysd** [comment]
I think it can solve this issue so I'll close this issue.  If you still have a problem, please reopen this issue.

**Comment by eduOS** [comment]
Thank you.
